### ISSUE TITLE
import my model but it cant detect the image 

### ISSUE THREAD

**Issue by Cello2115** [AndreyGermanov/yolov8_onnx_go#4]
i import my model ,its onnx file, but when i run the system,it didnt work normally,
file like this 
![image](https://github.com/AndreyGermanov/yolov8_onnx_go/assets/46987928/cbbdd6dc-291f-4da9-ab6c-6af5c95b1bcb)
and model in this path
![image](https://github.com/AndreyGermanov/yolov8_onnx_go/assets/46987928/e84930ca-042b-4211-acfe-991aec1e5fc1)
and i change the path in global.go like this
![image](https://github.com/AndreyGermanov/yolov8_onnx_go/assets/46987928/7e127a9f-42df-4a24-b935-6f40f1759241)

**Comment by Cello2115** [comment]
Error running network: Got invalid dimensions for output: output0 for the following indices
 index: 1 Got: 84 Expected: 7
 Please fix either the inputs/outputs or the model.

**Comment by AndreyGermanov** [comment]
> Error running network: Got invalid dimensions for output: output0 for the following indices index: 1 Got: 84 Expected: 7 Please fix either the inputs/outputs or the model.

The application created for standard YOLOv8 model trained on COCO dataset, that detects 80 classes. If you replaced it to the new model, that detects 3 classes, you need to replace 80 to 3, and 84 to 7 in all places in the code. In particular:

https://github.com/AndreyGermanov/yolov8_onnx_go/blob/124a61fe8c2ac2dcbb193833df84079bc47a99b2/onnx_util.go#L21 - replace "84" to "7"

https://github.com/AndreyGermanov/yolov8_onnx_go/blob/124a61fe8c2ac2dcbb193833df84079bc47a99b2/imagex.go#L19 - replace "80" to "3"

But the "8400" should not be replaced anywhere, because it's constant YOLOv8 model number of rows.

**Comment by Cello2115** [comment]
solved,thanks!
